// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"

extern camera_state, led_state;

void open_Camera(lv_event_t * e)
{
  camera_state = 1;
}

void close_Camera(lv_event_t * e)
{
  camera_state = 0;
}

void open_LED(lv_event_t * e)
{
  led_state = 1;
}

void close_LED(lv_event_t * e)
{
  led_state = 0;
}

void change_blue(lv_event_t* e) {
  int blue_value = 0;
  blue_value = lv_slider_get_value(ui_blueSlider);  //ui_Slider1 ui.h文件
}

void change_red(lv_event_t* e) {
  int red_value = 0;
  red_value = lv_slider_get_value(ui_redSlider);  //ui_Slider4 ui.h文件
}

void change_green(lv_event_t* e) {
  int green_value = 0;
  green_value = lv_slider_get_value(ui_greenSlider);  //ui_Slider3 ui.h文件
}

void takeFoto(lv_event_t * e)
{

}