// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void open_Camera(lv_event_t * e);
void close_Camera(lv_event_t * e);
void takeFoto(lv_event_t * e);
void change_red(lv_event_t * e);
void change_green(lv_event_t * e);
void change_blue(lv_event_t * e);
void open_LED(lv_event_t * e);
void close_LED(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
