// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"

void open_Camera(lv_event_t * e)
{
	// Your code here
}

void close_Camera(lv_event_t * e)
{
	// Your code here
}

void takeFoto(lv_event_t * e)
{
	// Your code here
}

void change_red(lv_event_t * e)
{
	// Your code here
}

void change_green(lv_event_t * e)
{
	// Your code here
}

void change_blue(lv_event_t * e)
{
	// Your code here
}

void open_LED(lv_event_t * e)
{
	// Your code here
}

void close_LED(lv_event_t * e)
{
	// Your code here
}
