// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"

void ui_Screen3_screen_init(void)
{
ui_Screen3 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_redSlider = lv_slider_create(ui_Screen3);
lv_slider_set_range(ui_redSlider, 0,255);
lv_slider_set_value( ui_redSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_redSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_redSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_redSlider, 20);
lv_obj_set_height( ui_redSlider, 180);
lv_obj_set_x( ui_redSlider, -10 );
lv_obj_set_y( ui_redSlider, -20 );
lv_obj_set_align( ui_redSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_redSlider, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_redSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_redSlider, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_redSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_redSlider, lv_color_hex(0xFF0000), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_redSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_greenSlider = lv_slider_create(ui_Screen3);
lv_slider_set_range(ui_greenSlider, 0,255);
lv_slider_set_value( ui_greenSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_greenSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_greenSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_greenSlider, 20);
lv_obj_set_height( ui_greenSlider, 180);
lv_obj_set_x( ui_greenSlider, -80 );
lv_obj_set_y( ui_greenSlider, -20 );
lv_obj_set_align( ui_greenSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_greenSlider, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_greenSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_greenSlider, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_greenSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_greenSlider, lv_color_hex(0x00FF00), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_greenSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_blueSlider = lv_slider_create(ui_Screen3);
lv_slider_set_range(ui_blueSlider, 0,255);
lv_slider_set_value( ui_blueSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_blueSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_blueSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_blueSlider, 20);
lv_obj_set_height( ui_blueSlider, 180);
lv_obj_set_x( ui_blueSlider, -150 );
lv_obj_set_y( ui_blueSlider, -20 );
lv_obj_set_align( ui_blueSlider, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_blueSlider, lv_color_hex(0xC8C8C8), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_blueSlider, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_blueSlider, lv_color_hex(0x0000FF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_blueSlider, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_blueSlider, lv_color_hex(0x0000FF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_blueSlider, 255, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Button3 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button3, 80);
lv_obj_set_height( ui_Button3, 40);
lv_obj_set_x( ui_Button3, 125 );
lv_obj_set_y( ui_Button3, -50 );
lv_obj_set_align( ui_Button3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Button3);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -2 );
lv_obj_set_y( ui_Label2, -1 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"ON");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Button4 = lv_btn_create(ui_Screen3);
lv_obj_set_width( ui_Button4, 80);
lv_obj_set_height( ui_Button4, 40);
lv_obj_set_x( ui_Button4, 125 );
lv_obj_set_y( ui_Button4, 40 );
lv_obj_set_align( ui_Button4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Button4);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, -2 );
lv_obj_set_y( ui_Label3, -1 );
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"OFF");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_redSlider, ui_event_redSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_greenSlider, ui_event_greenSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_blueSlider, ui_event_blueSlider, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Screen3, ui_event_Screen3, LV_EVENT_ALL, NULL);

}
